os:
  - linux
  - osx

language: node_js
node_js:
  - '6'
  - '7'
  - '8'

# addons:
#   chrome: stable

# before_install:
#   - export CHROME_BIN=/usr/bin/google-chrome
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - npm test
  - npm run test:npm && echo 'Npm packing test passed'

cache:
  directories:
    - node_modules

notifications:
  webhooks:
    urls:
      - ${GITTER_IM_URL}
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_deploy:
  - npm version
  - grep version package.json

deploy:
  provider: npm
  email: zixia@zixia.net
  api_key: "$NPM_TOKEN"
  skip_cleanup: true

